export const shipmentFormActionTypes = {
  ADD_SHIPPER_INFO: "@@SHIPMENT/ADD_SHIPPER_INFO",
  ADD_SHIP_TO_INFO: "@@SHIPMENT/ADD_SHIP_TO_INFO",
  ADD_PACKAGE_INFO: "@@SHIPMENT/ADD_PACKAGE_INFO",
  ADD_RATE_OPTIONS:"@@SHIPMENT/ADD_RATE_OPTIONS",
  SET_RATE_ID_SELECTED: "@@SHIPMENT/SET_RATE_ID_SELECTED",
  SET_NEXT_STEP: "@@SHIPMENT/SET_NEXT_STEP",
  SET_PREVIOUS_STEP: "@@SHIPMENT/SET_PREVIOUS_STEP",
  SET_LABEL_URL: "@@SHIPMENT/SET_LABEL_URL",
  RESET_FORM: "@@SHIPMENT/RESET_FORM"
};
